# Trích đoạn mã nguồn cấu hình Workflow
name: 'Terraform CI/CD with Checkov'
on:
  push:
    branches: [ "main" ]
permissions: read-all # Chỉ cấp quyền đọc (read) cho GitHub Token
env:
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  AWS_REGION: 'ap-southeast-1'

jobs:
  terraform:
    name: 'Terraform Plan and Apply'
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Set up Python & Install Checkov
      run: |
        pip install checkov==3.2.0

    - name: Run Checkov scan
      run: checkov -d . --soft-fail # Dùng soft-fail để cảnh báo lỗi nhưng vẫn cho pipeline chạy tiếp

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v2

    - name: Terraform Init, Plan and Apply
      run: |
        terraform init
        terraform plan
        terraform apply -auto-approve